#!/usr/bin/env lua

local home = os.getenv("HOME")
local config_dir = home .. "/.config/sketchybar"

package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path
  .. ";"
  .. config_dir
  .. "/?.lua;"
  .. config_dir
  .. "/?/init.lua"

local sbar = require("sketchybar")

sbar.begin_config()
require("bar")(sbar)
require("items.left")(sbar, config_dir)
require("items.right")(sbar, config_dir)
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
